### ISSUE TITLE
Throw an error if missing terraform backend

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#110]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

It would be nice if atmos would throw an error if a backend is missing from the terraform component. This would only apply for atmos 1.x if autogenerating the backend is set to false.

If atmos detects no backend, it could even suggest enabling this or at the very least show a warning that a backend is missing

fyi the existing setting in atmos.yaml

```
    # Can also be set using `ATMOS_COMPONENTS_TERRAFORM_AUTO_GENERATE_BACKEND_FILE` ENV var, or `--auto-generate-backend-file` command-line argument
    auto_generate_backend_file: false
```

**Comment by aknysh** [comment]
this is implemented
