### ISSUE TITLE
"can't find a shell to execute" when executing `atmos terraform shell [...]`

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/atmos#114]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Executing the `atmos terraform shell` command fails with

> can't find a shell to execute

## Expected Behavior
A shell would open

## Steps to Reproduce
1. Run Geodesic 
2. Install Atmos v1.3.26
3. Go to a terraform directory
4. Execute a shell for a component: `atmos terraform shell system -s gbl-root`
5. See that atmos command results in `can't find a shell to execute`

## Screenshots
N/A

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Linux 
 - Version: `Geodesic 0.149.1 based on Debian GNU/Linux 10 (buster) (10.11)`

## Additional Context
```
 ✗ . [none] (HOST) oc-terraform ⨠ atmos terraform shell system -s gbl-root

Variables for the component 'system' in the stack 'gbl-root':

REDACTED

Writing the variables to file:
components/terraform/system/gbl-root-system.terraform.tfvars.json

Executing command:
/usr/bin/terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
REDACTED

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Command info:
Terraform binary: terraform
Terraform command: shell
Arguments and flags: []
Component: system
Stack: gbl-root
Working dir: components/terraform/system

Executing command:
/usr/bin/terraform workspace select gbl-root
Switched to workspace "gbl-root".

Starting a new interactive shell where you can execute all native Terraform commands (type 'exit' to go back)
Component: system
Stack: gbl-root
Working directory: components/terraform/system
Terraform workspace: gbl-root

Setting the ENV vars in the shell:
TF_CLI_ARGS_plan=-var-file=gbl-root-system.terraform.tfvars.json
TF_CLI_ARGS_apply=-var-file=gbl-root-system.terraform.tfvars.json
TF_CLI_ARGS_refresh=-var-file=gbl-root-system.terraform.tfvars.json
TF_CLI_ARGS_import=-var-file=gbl-root-system.terraform.tfvars.json
TF_CLI_ARGS_destroy=-var-file=gbl-root-system.terraform.tfvars.json

can't find a shell to execute

-> Run 'assume-role' to login to AWS with aws-vault
 ⧉  OC Toolbox
 ✗ . [none] (HOST) oc-terraform ⨠ echo $SHELL
/bin/bash
```

Terraform version: 
```
 ✗ . [none] (HOST) oc-terraform ⨠ terraform version
Terraform v1.0.0
```

Here is the error code in question that is getting executed, but I'm not sure why... I'll continue to debug and see if I can post a fix, but if not then I wanted to surface for others. 
https://github.com/cloudposse/atmos/blob/4ba3e8c1c96d4f0afc4d601b2027a6cc1ec2cdc5/internal/exec/utils.go#L655-L657

**Comment by Gowiem** [comment]
Fast update on this one: If you provide `SHELL` as an environment variable inline with the atmos command then this works as expected. As in the following will do the trick: 

```
SHELL=/bin/bash atmos terraform shell system -s gbl-root
```

But... That isn't intuitive and I'm not sure what is necessarily required. I'd say it's still a bug worth fixing. I'll dig into what's going on and see what's up.

**Comment by aknysh** [comment]
thanks @Gowiem 
`atmos` assumes the SHELL ENV var to be set (we don't want to hardcode `bin/bash` in Go code).
It's set on OSX.
If it's not set in some environments, we can do it in Dockerfile for the infra.

**Comment by Gowiem** [comment]
@aknysh Yeah, understood on needing it to be set.

In the above example where I don't include `SHELL` inline, it is set in the environment. i.e. running `env` shows `SHELL=/bin/bash` in the list of environment variables. Yet Atmos is not picking that up for some reason unless it's set inline with the atmos command.

**Comment by osterman** [comment]
Can you try running "export SHELL" then retry? If that fixes it, we can add that export to geodesic

**Comment by aknysh** [comment]
yes, `export` is required since `atmos` starts a new sub-process
@Gowiem

**Comment by Gowiem** [comment]
@osterman @aknysh That did the trick. TIL a new Linuxism... I never put together that child processes don't pick up env variables unless they're explicitly exported. Probably because I *always* use `export`.

This is due to my lack of understanding, so closing out. But we should update Geodesic to call `export SHELL` as that seems like it'll be useful both here and elsewhere.

**Comment by aknysh** [comment]
thanks @Gowiem , we'll update geodesic
