### ISSUE TITLE
Atmos fails when using the s3 backend if not logged in

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#116]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Problem: Atmos fails when using the s3 backend if not logged in

It would be nice if atmos could fail early if `aws sts get-caller-identity` returns nothing... or whatever golang sdk can quickly see if we currently have a logged-in session within aws.

This could also be a new input param in atmos.yaml.

**Comment by osterman** [comment]
There's no practical/generic way to implement this as backends can be implemented any number of ways. We do not want to build in native checking for just AWS, as atmos is in use across enterprises in all sorts of clouds. Alternatively, you could propose a solution of running pre-flight checks as hooks containing any command(s) or referencing workflows. That sort of generic implementation would be acceptable.
