### ISSUE TITLE
Increase Parsing Error Verbosity to Include YAML Filename

### ISSUE THREAD

**Issue by srhopkins** [cloudposse/atmos#127]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Provide additional details on `atmos` errors resulting from stack config parsing issues.

Currently if any stack config yaml is malformed you will get an error indicating a failing line number but no indication which file is causing issues. The only current method I have found to get this is to run a script or loop through something like jq/yq until you get an error.

```
atmos terraform plan config-bucket --stack core-use2-audit
Found ENV var ATMOS_BASE ...
...
yaml: line 68: did not find expected key
```

## Expected Behavior

It would be desirable to have additional verbosity in the error that indicated the failing file.

```
atmos terraform plan config-bucket --stack core-use2-audit
Found ENV var ATMOS_BASE ...
...
iam-primary-roles.yaml: line 68: did not find expected key
```

## Use Case

Decrease troubleshooting time

## Describe Ideal Solution

A clear and concise description of what you want to happen. If you don't know, that's okay.

## Alternatives Considered

Explain what alternative solutions or features you've considered.

Script, jq, yq, etc

**Comment by srhopkins** [comment]
May relate to #88

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/atmos/pull/146
