### ISSUE TITLE
Atmos `version` not being embedded in `darwin_amd64` binary

### ISSUE THREAD

**Issue by korenyoni** [cloudposse/atmos#129]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

The Atmos version is not being properly embedded on Darwin AMD64 releases.

## Expected Behavior

The Atmos version should be embedded properly just as it is currently embedded in Linux.

## Steps to Reproduce
1. Download latest `darwin_amd64` release
2. Run `atmos version`
3. See `0.0.1`

## Screenshots

```bash
$ atmos version
0.0.1
```

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Darwin (macOS Big Sur)
 - Version `1.4.0`

## Additional Context

This implementation works fine on `linux_amd64`

```bash
$ atmos version
1.4.0
```

The implementation itself is quite clear. We use ldflags to override `cmd.Version` using the environment variable exposed by goreleaser:

https://github.com/cloudposse/atmos/blob/c9c63b04c9a2bfea70db6c59ed69b9d7594f952d/.goreleaser.yml#L7-L27

Not sure why it's not working as expected.

**Comment by aknysh** [comment]
this is working.
Download a darwin release, then run

```
chmod +x atmos_1.4.11_darwin_amd64
./atmos_1.4.11_darwin_amd64 version
```

The correct version (GitHub release) gets embedded into the binary when cutting releases on GitHub.
if you build locally, the version that gets embedded is taken from the Makefile

```
VERSION=test3
```
