### ISSUE TITLE
Logging/debug information should be sent to stderr, not stdout

### ISSUE THREAD

**Issue by Nuru** [cloudposse/atmos#140]
## Describe the Bug
When running a command like
```
atmos describe stacks --format=json | jq 
```
diagnostic/logging information such as
```
Found ENV var ATMOS_BASE_PATH=/localhost/devsrc
```
is output to `stdout`, breaking the pipeline by sending non-JSON to `jq`.

Although this is a particularly damaging issue for `describe stacks --format=json`, it is a general problem throughout `atmos` that prevents being able to parse the output of atoms commands. 

## Expected Behavior
Logging and diagnostic information should go to `stderr`.

Alternatively, you can provide a flag or `atmos.yaml` setting to suppress such output altogether, or a command-line option to send it to a separate file (e.g. `/dev/fd/2` or `/dev/null`).

## Environment:

`atmos` version 1.4.7

**Comment by aknysh** [comment]
we don't want to send info messages to `stderr` for various reasons.
we need to add LOG levels (e.g. INFO, DEBUG, ERROR, etc.) instead of the binary choice `verbose=true|false`

**Comment by osterman** [comment]
@aknysh I don't understand why `atmos` logging cannot be sent to `stderr`.

**Comment by aknysh** [comment]
> @aknysh I don't understand why `atmos` logging cannot be sent to `stderr`.

In some GH actions anything sent to stderr is considered an error (as @mcalhoun  can confirm).

All of the logging was improved in https://github.com/cloudposse/atmos/releases/tag/v1.33.0 - you can set any log level and/or specify log file
