### ISSUE TITLE
Inspiration section

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#169]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Since this is a universal tool of tools, we have learned (and evolved) from a lot of tools like the following

- variant
- ahoy
- choria-io

And I think this should be shown in an inspiration section. We agreed to this in a previous PR https://github.com/cloudposse/atmos/pull/168 and I wrote this up so we do not forget about it.

**Comment by osterman** [comment]
This was mostly addressed in https://atmos.tools/reference/alternatives
