### ISSUE TITLE
Switching between atmos versions (asdf plugin)

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#170]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Sometimes I need to switch between atmos versions in order to debug something or perhaps a client uses version X and another client uses version Y. I usually have to run another `go install` of a specific atmos release or use `apt install atmos="<version>-*"` from geodesic.

It would be nice to use a tool like `asdf` with an `atmos` plugin. This will put atmos on par with terragrunt

https://asdf-vm.com/
https://github.com/asdf-vm/asdf
https://github.com/asdf-vm/asdf-plugins

Another advantage of supporting `asdf` is that we can pin versions of `atmos` using the asdf [`.tool-versions`](https://github.com/asdf-vm/asdf/blob/master/.tool-versions) file for users that want to use `atmos` within geodesic and from outside.

This will allow using commands like this to download and pin the version using a `.tool-versions` file

```
asdf plugin install atmos
asdf atmos install latest
asdf local atmos latest
```

**Comment by osterman** [comment]
@nitrocode whipped this up! Let me know if it works for you.

https://github.com/cloudposse/asdf-atmos

**Comment by osterman** [comment]
Let's open up subsequent issues on the other repo.

**Comment by osterman** [comment]
https://github.com/asdf-vm/asdf-plugins/pull/1042
