### ISSUE TITLE
Official container on DockerHub, AWS Public ECR

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#214]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Official docker container on dockerhub, ghcr with alpine or scratch

## Expected Behavior

Run something like this for ghcr

```sh
$ docker run -it --rm \
  ghcr.io/cloudposse/atmos:v1.10.3 \
  1.10.3
```

Run the same for dockerhub so same above command except the image would be `cloudposse/atmos:v1.10.3`

## Use Case

- Be able to run atmos commands without installing
- Possibly use spacelift to run an atmos container

**Comment by osterman** [comment]
Good point. We should have that. I am down for it if you want to take a stab at it.

**Comment by llpham14** [comment]
https://cloudposse.atlassian.net/browse/DEV-904

**Comment by osterman** [comment]
This was completed in:
- #627
