### ISSUE TITLE
Stack file imports break on secondary relative paths

### ISSUE THREAD

**Issue by johncblandii** [cloudposse/atmos#24]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

Atmos v0.16.0 seems to be different from 0.10.0 of the stack-config module in TF.

Atmos requires a full path for an import based on the stack location.

`stacks/ue1-corp.yaml`:

```yaml
import:
  - eks/eks-defaults
```

That's fine in a stack, but importing from `eks-defaults` requires a relative path from the stack file:

`stacks/eks/eks-defaults.yaml`:

```yaml
import:
  - eks/eks-gbl-defaults
```

Just doing a relative fails to find the file when using Atmos. So `stacks/ue1-corp.yaml` imports `stacks/eks/eks-defaults.yaml` imports `stacks/eks/eks-gbl-defaults.yaml` and that could go on and on in other scenarios.

When using the TF module, it respects the import as relative from the point of the file importing it. So getting Atmos to work will break the TF module:

```bash
Error: open ../../../stacks/eks/eks/eks-gbl-defaults.yaml: no such file or directory
```

### Directory Structure

```bash
➜ tree .
.
├── eks
│   ├── eks-defaults.yaml
│   └── eks-gbl-defaults.yaml
├── gbl-globals.yaml
├── gbl-corp.yaml
├── globals.yaml
└── ue1-corp.yaml
```

## Expected Behavior

Imports from within an import should respect the current folder location of the file so relative paths work regardless of what parent file (stack or otherwise) did the initial import.

`stacks/eks/eks-defaults.yaml`:

```yaml
import:
  - eks-gbl-defaults
```

^ This should be perfectly fine 

## Steps to Reproduce

1. Create the files/directory structure
2. Run a `atmos terraform plan` without a relative path from the `stacks/` dir

## Screenshots

N/A

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: macOs
 - Version 11.2.1

## Additional Context

I believe that's it

**Comment by aknysh** [comment]
closing since this is updated (and new functionality added) in the new version of atmos starting with `1.0.0`
