### ISSUE TITLE
Add support for `terraform refresh`

### ISSUE THREAD

**Issue by johncblandii** [cloudposse/atmos#26]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

`terraform refresh` is missing from the available commands.

## Expected Behavior

Allow use of `terraform refresh`.

## Use Case

> The `terraform refresh~ command is used to reconcile the state Terraform knows about (via its state file) with the real-world infrastructure. This can be used to detect any drift from the last-known state, and to update the state file.

https://www.terraform.io/docs/cli/commands/refresh.html

## Describe Ideal Solution

It supports the same flow as `terraform output`.

## Alternatives Considered

N/A

## Additional Context

N/A

**Comment by Gowiem** [comment]
@johncblandii wonder if this is necessary anymore considering `terraform apply -refresh-only` is a thing now... What do you think?

**Comment by johncblandii** [comment]
Writing that in Atmos syntax would be `atmos terraform plan -s stack-name --args="--refresh-only"`.

That doesn't feel as easy to remember/write.

**Comment by Gowiem** [comment]
@johncblandii solid point 👍

**Comment by osterman** [comment]
Atmos now supports passthrough of all arguments to terraform with the 1.0 release
