### ISSUE TITLE
`terraform clean` should remove the lock file

### ISSUE THREAD

**Issue by johncblandii** [cloudposse/atmos#28]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

`atmos terraform clean [project]` does not remove the `.terraform.lock.hcl` file.

## Expected Behavior

`atmos terraform clean [project]` should remove the `.terraform.lock.hcl` file.

## Use Case

Cleaning a project

## Describe Ideal Solution

Just works

## Alternatives Considered

Manually deleting the file

## Additional Context

TF 0.14 introduced the lock file.

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/atmos/pull/42
