### ISSUE TITLE
Add Support for Commenting on PR with Affected Stacks

### ISSUE THREAD

**Issue by osterman** [cloudposse/atmos#282]
## Describe the Feature

Atmos should support native GitHub integration to comment on a PR (or issue) with a markdown formatted comment of the affected stacks.

It should support creating or updating an existing comment based on a regex pattern (so it's stateless).

The markdown template should be a property of the `atmos.yaml` so it can be customized.

It should probably be a feature flag of `atmos describe affected`, so the affected stacks do not need to be recomputed. In other words, we still need the JSON output to work with other github actions. 

## Expected Behavior

```
atmos describe affected --output json --github-issue-id 123
```

The above command would output the affected stacks as JSON and comment on the GitHub Issue #123 with a markdown formatted comment. The repo and github org would default to what is in the `.github/config` file of the current working repository.

## Use Case

- GitOps with GitHub Actions or general CI/CD would be easier to implement since comments would be posted
- Spacelift Rego policies can parse GitHub comments and only plan affected stacks

**Comment by mcalhoun** [comment]
@osterman Why add this as a feature to atmos? We're already outputting yaml/json and there is tons of prior art (github actions) that can post a comment...seems like unnecessary code for us to maintain unless I'm missing an important nuance.

**Comment by osterman** [comment]
This is not planned. It's job of the CI/CD implementation to make whatever comments are needed.
