### ISSUE TITLE
v1.19.0 release has no binaries

### ISSUE THREAD

**Issue by davenicoll** [cloudposse/atmos#291]
## Describe the Bug
The v1.19.0 release has no binaries packaged, only source code.

## Expected Behavior
The release contains updated binaries.

**Comment by aknysh** [comment]
@davenicoll  thanks for reporting this, our  build process failed b/c `goreleaser` released a new incompatible version.

Please use https://github.com/cloudposse/atmos/releases/tag/v1.19.1

**Comment by davenicoll** [comment]
Thanks!
