### ISSUE TITLE
inherits.component only accepts one path slash instead of several

### ISSUE THREAD

**Issue by hypnotisttom** [cloudposse/atmos#333]
### Describe the Bug

I want to organize my components with folders.  When I attempted to create something like path/to/component, atmos failed writing out the variables.  What I noticed is the variable path was taking one of the slashes and trying to use that.  When I changed it to something like path/component (i.e. only 1 slash), it worked.

### Expected Behavior

Atmos should accept multiple (or at least a reasonable number of) paths in a inherits.component string.

### Steps to Reproduce

1. Create a path such as components/terraform/path/to/component
2. Create a stack that inherits from that component
3. Run the plan

Plan will fail with error like:
```
Writing the variables to file:
components/terraform/path/to/component/self-ue2-eng-path/to-mycomponent.terraform.tfvars.json
open components/terraform/path/to/component/self-ue2-eng-path/to-mycomponent.terraform.tfvars.json: no such file or directory
```

If I instead use path/component, the variable line works and says:
```
Writing the variables to file:
components/terraform/path/component/self-ue2-eng-path-mycomponent.terraform.tfvars.json
```

### Environment

Linux
Atmos version 1.24.0

**Comment by aknysh** [comment]
@hypnotisttom thanks for reporting this.
I can confirm that the issue exists, and we'll fix it.
(it's not related to "inherits.component string" though, it's related to the paths)

**Comment by hypnotisttom** [comment]
You are the best @aknysh!
