### ISSUE TITLE
Quickstart: orgs/**/*.yaml in config causes issues on first run

### ISSUE THREAD

**Issue by hans-d** [cloudposse/atmos#398]
### Describe the Bug

Following the quickstarter (website/docs/quick-start/configure-repository.md), the atmos config is shown and some directories are created. When doing the first vendor pull, it complains about the orgs/**/*.yaml setting

### Expected Behavior

Tutorial can be followed without issues

### Steps to Reproduce

Follow the tutorial

**Comment by osterman** [comment]
Vendoring no longer requires any existing stack configurations
- #782 
- #768
