### ISSUE TITLE
Add a SECURITY.md file for a public security policy for this repo

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#450]
### Describe the Feature

https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

>To give people instructions for reporting security vulnerabilities in your project, you can add a SECURITY.md file to your repository's root, docs, or .github folder. When someone creates an issue in your repository, they will see a link to your project's security policy.

Here is an example

- https://github.com/ory/examples/blob/master/SECURITY.md

### Expected Behavior

- `SECURITY.md` in repo root

### Use Case

Help bolster the argument that this tool is secure by meeting the security threshold for high-security-needs companies

### Describe Ideal Solution

- `SECURITY.md` in repo root

### Additional Context

- https://github.com/cloudposse/atmos/security

**Comment by osterman** [comment]
This is live https://github.com/cloudposse/atmos?tab=security-ov-file
