### ISSUE TITLE
unable to install customized quickstart image

### ISSUE THREAD

**Issue by patlachance** [cloudposse/atmos#490]
### Describe the Bug

Tried to change the *DOCKER_ORG*, *DOCKER_IMAGE* and *DOCKER_TAG* in the **Makefile** file, build the container and then install it using `make install` but it tries installing the `cloudposse/atmos` image instead of the customized one.

### Expected Behavior

Running `make install` should install by customized image

### Steps to Reproduce

Clone the repo, patch the Makefile and build the container image

```shell
$ git clone
$ cd examples/quickstart
$ sed -i -e 's/DOCKER_ORG ?= cloudposse/DOCKER_ORG ?= myorg/' Makefile
$ sed -i -e 's/DOCKER_IMAGE ?= $(DOCKER_ORG)\/atmos/DOCKER_IMAGE ?= $(DOCKER_ORG)\/myatmos/' Makefile
$ make init build
```

Try to install the image

```shell 
$ make install
# Installing newatmos from cloudposse/atmos:latest...
Unable to find image 'cloudposse/atmos:latest' locally
docker: Error response from daemon: pull access denied for cloudposse/atmos, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

# Failed to install newatmos
# If this is not due to file system permissions, please
# check for known issues and consider reporting the failure at
#    https://github.com/cloudposse/geodesic/issues

Try: sudo make install
make: *** [Makefile:35: install] Error 1
```

==> The default **cloudposse/atmos** image is used instead of the customized one.

Changing the following section of the Makefile from 

```
install:
	@docker run --rm $(DOCKER_IMAGE_NAME) | bash -s $(DOCKER_TAG) || (echo 
```

to 

```
install:
	@docker run --rm -e DOCKER_IMAGE -e DOCKER_TAG $(DOCKER_IMAGE_NAME) | bash -s $(DOCKER_TAG) || (echo 
```

will fix the issue, I'll provide a pull request soon.

**Comment by osterman** [comment]
#612 introduces a devcontainer and simpler demos to get started. I think this is the direction we'll go, instead of investing in the tutorial repo.
