### ISSUE TITLE
Latest release `v.1.54.0` did not publish standard packages

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/atmos#509]
### Describe the Bug

Latest release did not include all packages 

![CleanShot 2024-01-13 at 20 34 09@2x](https://github.com/cloudposse/atmos/assets/1392040/ef99c841-f29a-4622-8e73-4a6c8eef21ec)

### Expected Behavior

Expect packages to exist so I can install. 

### Steps to Reproduce

1. Try install atmos v1.54.0 via [aqua](https://aquaproj.github.io/docs)

### Screenshots

N/A	

### Environment

N/A

**Comment by osterman** [comment]
This is now fiexed

**Comment by osterman** [comment]
https://github.com/cloudposse/atmos/releases/tag/v1.54.0
