### ISSUE TITLE
Extra debug output for template execution errors

### ISSUE THREAD

**Issue by joberly** [cloudposse/atmos#596]
### Describe the Feature

Provide extra template error context or debug data when internally generated templates fail to parse or execute.

### Expected Behavior

When a template error occurs, return extra debug data for the template error to use as an aid to find the problematic stack or component code.

### Use Case

Atmos-generated template parsing or execution failures at least sometimes result in very vague error messages like this:

```
template: all-atmos-sections:472: function "account" not defined
```

It would be beneficial if there was some extra context for this internally generated template for debug as the line number in the error message only corresponds to an internally generated template.

### Describe Ideal Solution

Something like the following is probably ideal but perhaps a bit complicated:

```
template: all-atmos-sections:472: function "account" not defined
  in template "all-atmos-sections":
  472:         description: value for {{ account }}
```

### Alternatives Considered

An option to dump the entire template to stderr or some kind of debug log/file would work, too.

**Comment by GabisCampana** [comment]
@aknysh [DEV-2148 : Extra debug output for template execution errors](https://linear.app/cloudposse/issue/DEV-2148/extra-debug-output-for-template-execution-errors)

**Comment by osterman** [comment]
@joberly please include the current behavior your experiencing. Also makes it easier to search for issues.

**Comment by osterman** [comment]
Closed in:
- #672
- #674
