### ISSUE TITLE
Support `.yml` ending for `component.y[a]ml`

### ISSUE THREAD

**Issue by kevcube** [cloudposse/atmos#610]
### Describe the Feature

The tool is strict about needing `component.yaml`, file ending for yaml files is a matter of preference and both should be accepted.

### Expected Behavior

Support `.[yml|yaml]` file ending

### Use Case

--

### Describe Ideal Solution

--

**Comment by GabisCampana** [comment]
@aknysh [DEV-2261 : Support `.yml` ending for `component.y\[a\]ml`](https://linear.app/cloudposse/issue/DEV-2261/support-yml-ending-for-componenty[a]ml)

**Comment by RoseSecurity** [comment]
Thank you for this suggestion! This feature is available in `1.91.0`
