### ISSUE TITLE
1.79.0 atmos version outputs 0.0.1 and advises to update

### ISSUE THREAD

**Issue by verygitmuchhub** [cloudposse/atmos#622]
### Describe the Bug

With atmos `1.79.0` `atmos version` spits:

> Atmos 0.0.1 on linux/amd64
>
> Your version of Atmos is out of date. The latest version is 1.79.0

### Expected Behavior

`atmos version` should print the correct version and should not advise me to update :)

### Steps to Reproduce

`atmos version`

**Comment by verygitmuchhub** [comment]
I deem that being an issue with the build pipeline and therefor being present in all compilation targets. In my case it's Linux amd64, if that helps anything.

**Comment by osterman** [comment]
Eek, I think you're right. 

<img width="1010" alt="image" src="https://github.com/cloudposse/atmos/assets/52489/a0c81efd-edae-4cb9-b93c-8037ab6c3fc7">

This probably broke with #586

**Comment by osterman** [comment]
This was resolved in a couple PRs. Latest issue should be resolved with 
- cloudposse/.github#108
