### ISSUE TITLE
Do not create workspace if overridden by environment TF_WORKSPACE

### ISSUE THREAD

**Issue by dennisroche** [cloudposse/atmos#653]
### Describe the Bug

In our deployment pipeline, we create the TF workspace via HTTP API as need to configuration not possible from `backend.tf`, e.g. `working-directory`, `global-remote-state`, etc. 

Once the workspace is created/checked, it sets the `TF_WORKSPACE` variable. 

In setting Atmos for the first time, found what I think is incorrect behaviour. 

```
Terraform has been successfully initialized!

Command info:
  Terraform binary: terraform
  Terraform command: plan
  Arguments and flags: []
  Component: ecr/redacted-app
  Terraform component: ecr
  Stack: redacted-dev
  Working dir: components/terraform/ecr

Executing command:
/usr/bin/terraform workspace select long_complex_workspace_name_redacted
The selected workspace is currently overridden using the TF_WORKSPACE
environment variable.
To select a new workspace, either update this environment variable or unset
it and then run this command again.

Executing command:
/usr/bin/terraform workspace new long_complex_workspace_name_redacted
Workspace "new long_complex_workspace_name_redacted" already exists
exit status 1
```
 ### 

### Expected Behavior

If the workspace is overridden by `TF_WORKSPACE`, then `atmos` should accept that it is managed elsewhere and don't try create it again. 

### Steps to Reproduce

Run `atmos` with `TF_WORKSPACE` environment variable set. 

### Environment

- OS: Windows 11
- Atmos: 1.83.1
- Terraform: 1.8.2

### Additional Context

I think we could change the error handling in `~L394`

https://github.com/cloudposse/atmos/blob/8060adb59caa71b5b4ca3a489844070478feb361/internal/exec/terraform.go#L382-L409

**Comment by dennisroche** [comment]
Unfortunately, the `terraform workspace select` doesn't return a nuanced `exitCode` for this event.

https://github.com/hashicorp/terraform/blob/5868f994139db04a5f6989491f1dbb84486873ac/internal/command/workspace_select.go#L54C2-L58C3

So might need to add a check to see if `TF_WORKSPACE` is set, e.g. https://github.com/hashicorp/terraform/blob/125cf53470a3e9ada9e1c79cb077c3ca36a06607/internal/command/meta.go#L784C1-L801C2

**Comment by dennisroche** [comment]
I've workaround this for now by unsetting the `TF_WORKSPACE` environment and then using `terraform_workspace_template` to override the workspace.

 Note, `terraform_workspace_template` is not documented at https://atmos.tools/core-concepts/components/terraform/workspaces#terraform-workspace-override-in-atmos

**Comment by aknysh** [comment]
@dennisroche will it work for you if Atmos would check if the ENV variable `TF_WORKSPACE` is set by the caller and don't set TF workspace in this case? If the ENV var `TF_WORKSPACE` is not set, then do what it currently does.

We can add that functionality in the next release.

Thank you

**Comment by dennisroche** [comment]
@aknysh that should work. 

As I said, I've worked around this by using the `terraform_workspace_template` override; this might be a better solution as then we can `plan` stacks outside of the CICD.

Whilst searching for other issues, I just found a discussion on `TF_WORKSPACE` that might be relevant/past decision: https://github.com/cloudposse/atmos/issues/192

**Comment by osterman** [comment]
Fwiw, we snuck the requested support into this PR
- #654
