### ISSUE TITLE
Update "Simple Tutorial Docs"

### ISSUE THREAD

**Issue by shrihariharidass** [cloudposse/atmos#664]
## Issue

- In the Start Your Project Page, in the file system layout if you observe the component name is ```myapp``` and then on the next page ```Write Some Components``` you mention to Create a Directory for Your Component the command is 
```mkdir -p components/terraform/weather``` 
- But, in the ```Deploy Everything Page``` you mention the command as:
```atmos terraform apply myapp -s dev``` When I run this command I get an error called ```myapp``` component not found because I created ```Weather```
- So it is so confusing when I rename ```weather``` to ```myapp``` its work
- Again after changing I got a new error related ```Weather API``` but when I ```curl``` that ```API``` it working, the error I found in ```examples/quick-start-simple/stacks/deploy/dev.yaml``` where ```location: Stockholm```, when I change location to ```India``` its work, so I guess you need to change a location.
![Screenshot 2024-08-06 100623](https://github.com/user-attachments/assets/358c17cc-2b75-4f0c-abd1-9f856a9c4f99)
location to work fine your demo 

### Expected Behavior

- So because of what I mentioned in Bug, when I demonstrate it's not working as I mention that bug so can you please check once

### Steps to Reproduce

- As I mention I change ```Component``` name to ```weather``` to ```myapp```
- Also I change ```location```

**Comment by glensc** [comment]
for the myapp vs station, this fix is needed:

```diff
diff --git a/stacks/deploy/dev.yaml b/stacks/deploy/dev.yaml
index 388d721..b47f7f5 100644
--- a/stacks/deploy/dev.yaml
+++ b/stacks/deploy/dev.yaml
@@ -6,7 +6,7 @@ import:
 
 components:
   terraform:
-    myapp:
+    station:
       vars:
         location: Stockholm
         lang: see

```

to this file:
- https://github.com/cloudposse/atmos/blob/fec62aa78ef64c8e3d9b3f38f3377040f20748a4/examples/quick-start-simple/stacks/deploy/dev.yaml#L9

**Comment by osterman** [comment]
Thanks, missed this issue somehow. We will review and fix
