### ISSUE TITLE
Outdated terraform links

### ISSUE THREAD

**Issue by glensc** [cloudposse/atmos#682]
### Describe the Bug

on this page:
- https://atmos.tools/best-practices/terraform/#never-include-components-inside-of-other-components

both [Terraform Overrides](https://www.terraform.io/docs/language/modules/develop/override.html) and [Vendoring](https://www.terraform.io/docs/language/modules/develop/override.html#vendoring) are broken

also the "Edit" link at the bottom of the page:
- [Edit this page](https://github.com/cloudposse/atmos/edit/master/website/docs/best-practices/terraform.mdx)

**Comment by osterman** [comment]
Thanks for reporting! I think this was fixed in one of our latest updates, as the link is no longer broken for me.
