### ISSUE TITLE
README out of date now that golang version is live

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/atmos#72]
## Describe the Bug
`README.md` is fairly out of date as it still mentions variant2, developing your own CLI (I'm assuming this is no longer supported), and doesn't mention the now required configuration (`.atmos.yaml` and similar). 

## Expected Behavior
As a new engineer on-boarding to use `atmos` or an existing atmos user, I would expect that I can find out about the configuration options so I can avoid the error when the atmos configuration file is not found. 

## Steps to Reproduce
1. Read README.md

## Screenshots
N/A

## Environment (please complete the following information):

N/A

## Additional Context
N/A

**Comment by dre2004** [comment]
Related to the above there also quite a few broken links, mainly referring to old variant modules.

**Comment by Gowiem** [comment]
Closing this issue as it is no longer relevant -- README has been properly updated.
