### ISSUE TITLE
Examples refer to non-existent command: `atmos demo download `

### ISSUE THREAD

**Issue by tirelibirefe** [cloudposse/atmos#722]
### Describe the Bug

`atmos demo download demo-stacks`

Error: unknown command "demo" for "atmos"

### Expected Behavior

displaying something meaningful.

### Steps to Reproduce

install atmos
then run the command below:

`atmos demo download demo-stacks`

### Environment

macos
latest version macos and atmos

**Comment by osterman** [comment]
@tirelibirefe thanks for bringing this to our attention!


You're right that the commands in the `README.md` are wrong. We'll fix that, but `atmos` very much indeed works on a Mac (our whole team is using Macs).

```shell
atmos demo download <example>
```
 
```shell
atmos demo download demo-stacks
```

In the meantime, please have a look here if you're still exploring Atmos:  https://atmos.tools/quick-start/simple/
