### ISSUE TITLE
validate command prints usage when used like documented?

### ISSUE THREAD

**Issue by verygitmuchhub** [cloudposse/atmos#781]
### Describe the Bug

We bumped from 1.90.0 to 1.105.0. Our CI uses 

`atmos validate component <component> --stack <stack>`

With 1.105.0 (and 1.106.0) we now get the commands usage printed instead/additionally:

```
atmos validate component "vpc/foo" --stack bar
```

```
Atmos supports native '' commands with all the options, arguments and flags.

In addition, 'component' and 'stack' are required in order to generate variables for the component in the stack.

atmos  <subcommand> <component> -s <stack> [options]
atmos  <subcommand> <component> --stack <stack> [options]

For more details, execute ' --help'

component 'vpc/foo' in stack 'bar' validated successfully
```

So it looks like some validation still took place and it was successfull.

### Expected Behavior

Exit code 0 on successfull validation, some other number otherwise. No usage gets printed to the screen.

### Steps to Reproduce

Run `atmos validate component <component> --stack <stack>` as documented via `--help`.

### Environment

- OS: Linux
- atmos Version: 1.105.0
- terraform Version: 1.8.5

**Comment by osterman** [comment]
This is a regression. We will get it fixed ASAP.

**Comment by GabisCampana** [comment]
@aknysh

**Comment by Cerebrovinny** [comment]
@aknysh not able to found the regression checking this https://raw.githubusercontent.com/cloudposse/atmos/b53d696375a6716b2fd0bc024fb1861b46c78bb5/internal/exec/validate_stacks.go

maybe you can point out the root cause for this? also silence usage from cobra can be a viable option on this case

**Comment by aknysh** [comment]
@Cerebrovinny  i'll check it and let you know

**Comment by osterman** [comment]
This was resolved as part of:
- #825

**Comment by osterman** [comment]
These changes were released in [v1.119.0](https://github.com/cloudposse/atmos/releases/tag/v1.119.0).

**Comment by mss** [comment]
Unfortunately that PR didn't fix this issue:
```
± atmos version

 █████  ████████ ███    ███  ██████  ███████ 
██   ██    ██    ████  ████ ██    ██ ██      
███████    ██    ██ ████ ██ ██    ██ ███████ 
██   ██    ██    ██  ██  ██ ██    ██      ██ 
██   ██    ██    ██      ██  ██████  ███████ 
                                             

👽 Atmos 1.123.0 on linux/amd64

± atmos validate component wms-base --stack wms-xe02-sandbox

Atmos supports native '' commands with all the options, arguments and flags.

In addition, 'component' and 'stack' are required in order to generate variables for the component in the stack.

atmos  <subcommand> <component> -s <stack> [options]
atmos  <subcommand> <component> --stack <stack> [options]

For more details, execute ' --help'

component 'wms-base' in stack 'wms-xe02-sandbox' validated successfully
```

**Comment by mss** [comment]
The changelog for [v1.132.0](https://github.com/cloudposse/atmos/releases/tag/v1.132.0) has the entry "Do not show help when executing `atmos validate component <component> --stack <stack>` command" so hopefully this is fixed in that version (not verified yet).
