### ISSUE TITLE
Option to sanity check stack yaml

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#88]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Option to sanity check stack yaml

```
$ atmos validate stacks
```

This would be nice and it can be configured as a local pre-commit hook to prevent stack yaml issues from being committed.

Error that brought this up

```
+ atmos --config-dir ../../../stacks --terraform-dir ../ terraform write varfile acm --stack=uw2-dev
Error: Error in function call

  on /modules/utils/stack-config.variant line 71:
  (source code not available)

with opt.config-dir as "../../../stacks",
     opt.stack as "uw2-dev".

Call to function "import" failed: /modules/utils/stack-config.variant:12,13-20: Error in function
call; Call to function "import" failed: /modules/utils/stack-config.variant:10,43-50: Invalid
function argument; Invalid value for "path" parameter: no file exists at
../../../stacks/catalog/elasticache-redis/xyz.yaml;
```

**Comment by johncblandii** [comment]
I can't stop typing `imports` so checking `import` vs `imports` or supporting the plural (it is an array anyway) would be awesome for the sanity check as well. :)

(sorry to hijack; lol)

**Comment by nitrocode** [comment]
@johncblandii no worries, that's related to this issue. i created a separate one to track aliases https://github.com/cloudposse/atmos/issues/89.

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/atmos/pull/146
