### ISSUE TITLE
Support command and yaml aliases

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#89]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

```
atmos terraform output
atmos terraform outputs
```

in the stack yaml

```
import:
imports:
```

**Comment by osterman** [comment]
Relates more to #83. We should error if using invalid keys.

**Comment by osterman** [comment]
We do not plan to add this as it will lead too too many variations of the markup. We should strive for consistency.
