### ISSUE TITLE
Show components deployed per stack

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#97]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

It would be nice to see what components are in the stack

Perhaps something like `describe component` but for stacks.

```
atmos describe stack --stack ue2-corp
```

**Comment by aknysh** [comment]
implemented in https://github.com/cloudposse/atmos/pull/133
